# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180923_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lnvalid_date',
            field=models.CharField(default='', max_length=32, verbose_name='失效日期'),
            preserve_default=False,
        ),
    ]
