# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-23 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_lnvalid_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.IntegerField(choices=[(0, '注册密码'), (1, '找回密码')], verbose_name='验证码类型')),
                ('code', models.CharField(max_length=50, verbose_name='验证码')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
                ('active_status', models.BooleanField(default=0, verbose_name='激活状态')),
            ],
        ),
    ]
