# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='机房简称')),
                ('name_cn', models.CharField(max_length=32, verbose_name='机房中文名')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='机房地址，云厂商可以不写')),
                ('username', models.CharField(max_length=32, verbose_name='机房负责人')),
                ('username_phone', models.CharField(max_length=32, verbose_name='机房负责人联系电话')),
                ('phone', models.CharField(max_length=32, verbose_name='机房电话')),
                ('email', models.EmailField(max_length=254, verbose_name='机房邮箱')),
            ],
            options={
                'db_table': 'resources_idc',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='主机名')),
                ('cpu_info', models.CharField(max_length=64, verbose_name='CPU型号')),
                ('cpu_count', models.IntegerField(verbose_name='CPU物理个数')),
                ('mem_info', models.CharField(max_length=32, verbose_name='内存信息')),
                ('disk_info', models.CharField(max_length=64, verbose_name='硬盘信息')),
                ('ip_info', models.CharField(max_length=64, verbose_name='IP信息')),
                ('os_system', models.CharField(max_length=32, verbose_name='系统平台')),
                ('os_system_num', models.IntegerField(verbose_name='系统平台位数')),
                ('uuid', models.CharField(max_length=64, verbose_name='UUID')),
                ('sn', models.CharField(max_length=64, verbose_name='SN')),
                ('scan_status', models.IntegerField(choices=[(0, '连接异常'), (1, '连接正常')], verbose_name='探测状态')),
                ('info', models.CharField(max_length=64, verbose_name='备注')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建主机时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新主机时间')),
            ],
        ),
        migrations.CreateModel(
            name='ServerAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_inner', models.CharField(max_length=32, verbose_name='连接IP地址')),
                ('port', models.IntegerField(verbose_name='连接端口')),
                ('os_status', models.IntegerField(choices=[(0, 'Linux'), (1, 'Windows'), (2, 'Mac')], verbose_name='操作系统')),
                ('system_status', models.IntegerField(choices=[(0, '虚拟机'), (1, '物理机'), (2, '虚拟化')], verbose_name='机器类型')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='server_auto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.ServerAuto'),
        ),
    ]
